{
  "formatVersion": "1.1",
  "component": {
    "group": "ps.blockbuilders.paymentSdk",
    "module": "flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 4164486,
          "sha512": "22618894dadf05caff2249227d8d92aab1e710d0cd4d7b8ff74e9a642fbbbb5b1bc23753817d8ee2d4e4bbaf6b6c252bb5474f8dd4a7fc74c5a1f01d4083d071",
          "sha256": "0759beefe44846a0426d589aa0a1b0e0a8601fc40fd3298e8508f43ad53e5614",
          "sha1": "27b076aec05a06ebbdf3de7e238aeb1219638525",
          "md5": "43082e30808c391c8a2f6c870818625e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 4164486,
          "sha512": "22618894dadf05caff2249227d8d92aab1e710d0cd4d7b8ff74e9a642fbbbb5b1bc23753817d8ee2d4e4bbaf6b6c252bb5474f8dd4a7fc74c5a1f01d4083d071",
          "sha256": "0759beefe44846a0426d589aa0a1b0e0a8601fc40fd3298e8508f43ad53e5614",
          "sha1": "27b076aec05a06ebbdf3de7e238aeb1219638525",
          "md5": "43082e30808c391c8a2f6c870818625e"
        }
      ]
    }
  ]
}
