{
  "formatVersion": "1.1",
  "component": {
    "group": "ps.blockbuilders.paymentSdk",
    "module": "flutter_profile",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_profile",
          "version": {
            "requires": "1.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.3.aar",
          "url": "flutter_profile-1.0.3.aar",
          "size": 6558740,
          "sha512": "8d44403489bfeec5ce7bb8d36a51e0ffc95c09820edd48e1cf82bf2471338f8754064325d13b27cbb4f9fdb050a6da7076e59b471ed55092ac2999a7b5ca0c0c",
          "sha256": "1347b92d3a59cfd5910e1f42816fcad153202dc6a1392b7298a80dccf42c0b8c",
          "sha1": "431d98070632b03a9ccc44f46c90beadbe16e0ea",
          "md5": "f37c5055b44ec0a042aaef23db06a167"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_profile",
          "version": {
            "requires": "1.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.3.aar",
          "url": "flutter_profile-1.0.3.aar",
          "size": 6558740,
          "sha512": "8d44403489bfeec5ce7bb8d36a51e0ffc95c09820edd48e1cf82bf2471338f8754064325d13b27cbb4f9fdb050a6da7076e59b471ed55092ac2999a7b5ca0c0c",
          "sha256": "1347b92d3a59cfd5910e1f42816fcad153202dc6a1392b7298a80dccf42c0b8c",
          "sha1": "431d98070632b03a9ccc44f46c90beadbe16e0ea",
          "md5": "f37c5055b44ec0a042aaef23db06a167"
        }
      ]
    }
  ]
}
