{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-1.0.aar",
          "url": "webview_flutter_android_release-1.0.aar",
          "size": 148904,
          "sha512": "9141083586df8843f9f5d5a6c7df0b0d26cb93752fd3f4e69eb41a915cd9765219ff2c078c8f675ecb2a9ea4c4d15dc73f88ebdc0ec898f57c0a45f4bd2981db",
          "sha256": "3e3fb65accd6afc1ce4ff77a73e4a260609ac9f9b338d89e6a45691324977ff9",
          "sha1": "4f7d9ac95c66331c66dcbc90a3104745bf2a207f",
          "md5": "234fc676d0610757ed05c0efd82b4939"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-1.0.aar",
          "url": "webview_flutter_android_release-1.0.aar",
          "size": 148904,
          "sha512": "9141083586df8843f9f5d5a6c7df0b0d26cb93752fd3f4e69eb41a915cd9765219ff2c078c8f675ecb2a9ea4c4d15dc73f88ebdc0ec898f57c0a45f4bd2981db",
          "sha256": "3e3fb65accd6afc1ce4ff77a73e4a260609ac9f9b338d89e6a45691324977ff9",
          "sha1": "4f7d9ac95c66331c66dcbc90a3104745bf2a207f",
          "md5": "234fc676d0610757ed05c0efd82b4939"
        }
      ]
    }
  ]
}
