{
  "formatVersion": "1.1",
  "component": {
    "group": "ps.blockbuilders.paymentSdk",
    "module": "flutter_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 6558216,
          "sha512": "58f61f4a30498c9e9beea3d4e8582c12c528f4adb0203295d4993aca4665a86c358a597c8e3d511db0305702b721286c92777edcff0854ac88589758e96eab3b",
          "sha256": "75a5eed0b9e4a48caba8e63cbcba846956fc5083681fe2828dda1b5bd551acf4",
          "sha1": "d8ce8af6c3081b7c79cb6329f682a6e490bbb17b",
          "md5": "440b6a7712370e04d6e787c96ba8ad7a"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 6558216,
          "sha512": "58f61f4a30498c9e9beea3d4e8582c12c528f4adb0203295d4993aca4665a86c358a597c8e3d511db0305702b721286c92777edcff0854ac88589758e96eab3b",
          "sha256": "75a5eed0b9e4a48caba8e63cbcba846956fc5083681fe2828dda1b5bd551acf4",
          "sha1": "d8ce8af6c3081b7c79cb6329f682a6e490bbb17b",
          "md5": "440b6a7712370e04d6e787c96ba8ad7a"
        }
      ]
    }
  ]
}
