{
  "formatVersion": "1.1",
  "component": {
    "group": "ps.blockbuilders.paymentSdk",
    "module": "flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 4178163,
          "sha512": "ad1d7e3075a7a329055045d637b77b932222bfce40953eda5d7c3dff56a63067e4e8175f241ebaacb60e285b624e3eb5489a576ce737ab2be509917e3620e6b3",
          "sha256": "c46aad3cc6e4c3154d4ff8f9fa7e1aa3d2fcc8fc20bd287260eb08b4a35d69b6",
          "sha1": "11037cc4a9344b92ce921cb0a038154bf2748363",
          "md5": "ef06cb6f5b2109f62f19b176b89eef58"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 4178163,
          "sha512": "ad1d7e3075a7a329055045d637b77b932222bfce40953eda5d7c3dff56a63067e4e8175f241ebaacb60e285b624e3eb5489a576ce737ab2be509917e3620e6b3",
          "sha256": "c46aad3cc6e4c3154d4ff8f9fa7e1aa3d2fcc8fc20bd287260eb08b4a35d69b6",
          "sha1": "11037cc4a9344b92ce921cb0a038154bf2748363",
          "md5": "ef06cb6f5b2109f62f19b176b89eef58"
        }
      ]
    }
  ]
}
