{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_profile",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_profile-1.0.6.aar",
          "url": "webview_flutter_android_profile-1.0.6.aar",
          "size": 148907,
          "sha512": "38cf3555bdea5d9927514596eea13367fe16586f5bb9f0d9a271725ac3d71e5d640c703aa108352d5ee6c844310b983e0cb5553a3b975c6fda04b13405dda8c0",
          "sha256": "f666b761017a22be6c19afa21bbdaf3f9ffc5b1ba71c8282ffc816669761b69d",
          "sha1": "23f60a54a98a029422570fa5d1dbcbb9733de88f",
          "md5": "4a7e04284ef3b864e2def905eba68d60"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_profile-1.0.6.aar",
          "url": "webview_flutter_android_profile-1.0.6.aar",
          "size": 148907,
          "sha512": "38cf3555bdea5d9927514596eea13367fe16586f5bb9f0d9a271725ac3d71e5d640c703aa108352d5ee6c844310b983e0cb5553a3b975c6fda04b13405dda8c0",
          "sha256": "f666b761017a22be6c19afa21bbdaf3f9ffc5b1ba71c8282ffc816669761b69d",
          "sha1": "23f60a54a98a029422570fa5d1dbcbb9733de88f",
          "md5": "4a7e04284ef3b864e2def905eba68d60"
        }
      ]
    }
  ]
}
