{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_debug",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_debug-1.0.3.aar",
          "url": "webview_flutter_android_debug-1.0.3.aar",
          "size": 158145,
          "sha512": "bc5a756ddb3414e4518afecfea193f3244627dbdb2e8b03a140a57c0b3dde68722d0d52a286a2350f2a521bbf4064f115aa3448d56c6f6e3fec79b44e9ecca48",
          "sha256": "c2d69e3ef760d9c960328eab97e6b095d6ada8bd09412d2cf496b25ee451a709",
          "sha1": "74ef5ce7275ffcbe4f115787e1c62d7de6ce6120",
          "md5": "2d8f04314f70e78e5b23043078aea549"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-2e4ba9c6fb499ccd4e81420543783cc7267ae406"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_debug-1.0.3.aar",
          "url": "webview_flutter_android_debug-1.0.3.aar",
          "size": 158145,
          "sha512": "bc5a756ddb3414e4518afecfea193f3244627dbdb2e8b03a140a57c0b3dde68722d0d52a286a2350f2a521bbf4064f115aa3448d56c6f6e3fec79b44e9ecca48",
          "sha256": "c2d69e3ef760d9c960328eab97e6b095d6ada8bd09412d2cf496b25ee451a709",
          "sha1": "74ef5ce7275ffcbe4f115787e1c62d7de6ce6120",
          "md5": "2d8f04314f70e78e5b23043078aea549"
        }
      ]
    }
  ]
}
